# Generated by Django 3.2.6 on 2021-11-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fruit',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='fruit',
            name='image',
            field=models.CharField(default='https://st2.depositphotos.com/7520316/11068/v/950/depositphotos_110680048-stock-illustration-fruit-icon-fruit-sign.jpg', max_length=200),
        ),
    ]
