# Generated by Django 3.2.6 on 2021-11-27 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211127_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fruit',
            old_name='question_text',
            new_name='name',
        ),
    ]
